### ISSUE TITLE
Can't execute query from Spring Boot App

### ISSUE THREAD

**Issue by Afler** [edgedb/edgedb-java#35]
Running on Windows 10 and JDK corretto-17.0.8
I've tried to execute query like this: 
![image](https://github.com/edgedb/edgedb-java/assets/49097219/c8ae2b2d-be71-47bf-bdb5-da3c52e42d5c)

and get:
```
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:146) ~[na:na]
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:127) ~[na:na]
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297) ~[na:na]
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434) ~[na:na]
	... 36 common frames omitted

```

If i set TSLSecurity.INSECURE options then my whole app hang on this line
![image](https://github.com/edgedb/edgedb-java/assets/49097219/49ed1b0f-0a8f-43e4-b8a7-b9808f2125d7)

**Comment by Afler** [comment]
Ok it worked when I used suggested [project-based approach](https://docs.edgedb.com/libraries/connection) from documentation.
I assume my problem with manual config appeared because creating EdgeDBConnection and EdgeDBClientConfig drops its default values so I must to set all existing properties manually instead of overwrite one or two I wanted. I think adding method EdgeDBClientConfig.builder().getDefaultConfig().set~PropertyName~() would be good to ensure option to overwrite only desired config or connection properties;
